### ISSUE TITLE
Remed-exam

### ISSUE THREAD

**Issue by dudung** [dudung/sk6093-01-2023-2#10]
+ It is for [alitadinugraha](https://github.com/alitadinugraha)
  - https://github.com/dudung/sk6093-01-2023-2/issues/9
  - https://github.com/dudung/sk6093-01-2023-2/issues/8
+ Submit the tasks before ~29 Jun 2024, 2100~ 01 Jul 2024, 1800.

**Comment by alitadinugraha** [comment]
Through this message I would like to say thank you for the opportunity, given to carry out my remedial exams. Below I will tag a link to the remedial assignment that I have done. thank you for your attention.

- https://github.com/dudung/sk6093-01-2023-2/issues/9#issuecomment-2199354654
- https://github.com/dudung/sk6093-01-2023-2/issues/8#issuecomment-2199121985
