### ISSUE TITLE
Assigment 08 -- 08 May 2024

### ISSUE THREAD

**Issue by dudung** [dudung/sk6093-01-2023-2#9]
Explain about documentation of your repository, which should include
- How to contribute and create issues
- How to download / install / use the software / program / library
- Versions and bugs fixed

**Comment by NitaDwiFitriani** [comment]
Independent Research in Computational Science 3 (Assigment 08 )
Nita Dwi Fitriani (20922303)

Medium Assigment 08 :
https://medium.com/@nitadwifitriani/progress-report-9-f676396a1a66
Document Assigment 08 :
[Assigment 08_Nita Dwi Fitriani_20922303 .pdf](https://github.com/dudung/sk6093-01-2023-2/files/15271778/Assigment.08_Nita.Dwi.Fitriani_20922303.pdf)

**Comment by abraar4100** [comment]
___
**Final Assignment**
Muhammad Abraar Abhirama (20923003)
___

* [Medium](https://abraar4100.medium.com/a-simple-guide-to-applying-deep-reinforcement-learning-to-stock-portfolio-optimization-2e95e0720d6c)
* [PDF File of the Hands-on Module](https://github.com/user-attachments/files/15753499/SK6093_Final_Assignment_20923003_Muhammad_Abraar_Abhirama.pdf)
___
**All bugs fixed**

**Comment by alitadinugraha** [comment]
**Remed-exam**: Independent Research in Computational Science 3 (SK6093)
Dewa Made Alit Adinugraha (20922006)

- [Medium](https://medium.com/@alitadinugraha/a-brief-guide-of-sentiment-analysis-using-machine-learning-0496076c357c)
- [Modul Pembelajaran - 20922006.pdf](https://github.com/user-attachments/files/16048835/Modul.Pembelajaran.-.20922006.pdf)
